import subprocess
import time
import datetime

def get_status(name):
    out = ""
    err = ""
    result = subprocess.run(["vagrant", "ssh", name, "-c", "hostname -I"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if 0 != result.returncode:
        return ""
    else:
        s = result.stdout.decode("utf-8") 
        return s.split(" ")[1]
    

get_status("master")

while True:

    cluster = {}

    ip = get_status("master")
    if ip:
        cluster["master"] = f"{ip}"

    wi = 1
    while True:
        
        host = f"worker{wi}"
        ip = get_status(f"worker{wi}")
        if ip:
            cluster[host] = f"{ip}"
            wi += 1
        else:
            break
    
    with open("generated/hostfile/hostfile", "w") as f:
        now = datetime.datetime.now()
        f.write(f"# generated by hostfiler.py at {now}\n")
        for host in cluster:
            f.write(f"{cluster[host]} slots=1\n")

    with open("generated/hostfile/config", "w") as f:
        now = datetime.datetime.now()
        f.write(f"# generated by hostfiler.py at {now}\n")
        for host in cluster:
            f.write(f"Host {host}\n")
            f.write(f"  HostName {cluster[host]}\n")
            f.write("  PreferredAuthentications publickey\n")
            f.write("  StrictHostKeyChecking no\n")
            f.write("  UserKnownHostsFile=/dev/null\n")
            f.write("\n")

    print("sleep 5")
    time.sleep(5)

